version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
    open-pull-requests-limit: 3
    target-branch: main
    reviewers:
      - dscpinheiro
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
    open-pull-requests-limit: 1
    target-branch: main
    reviewers:
      - dscpinheiro
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
    open-pull-requests-limit: 1
    target-branch: main
    reviewers:
      - dscpinheiro
